### PR TITLE
Added file utils: Remove directory; Create Directory

### PR DESCRIPTION
**Pull request by yasasvee**
Looking around :)

### CODE REVIEW

**Comment by bharadwajturlapati** [comment]
Shutil needs to be imported i guess.
Will merge and test the code :)

**Comment by bharadwajturlapati** [comment]
merged no confilcts :)

**Comment by yasasvee** [comment]
Added import as per review comment :P

P.S.: Consequences of not forking and committing initially :D

**Comment by yasasvee** [comment]
Did unit testing in the terminal(Py interpreter) from my side. :dart:

**Pull request merged**
